[build]
  command = "npm run build"
  publish = "dist"
[[redirects]]
  from = "/infrastructure/*"
  to = "/infrastructure/:splat"
  status = 200
  force = false
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
