export const categories = [
  'angular',
  'react',
  'testing',
  'branding',
  'design',
  'software-development',
  'javascript',
  'typescript',
  'software-architecture',
  'design-patterns',
  'css',
  'personal-development',
  'yearly-review',
  'writing',
] as const
