export const TYPES = {
  TRANSLATOR_TYPE: Symbol('TRANSLATOR_TYPE'),
  ENCODER_SERVICE_TYPE: Symbol('ENCODER_SERVICE_TYPE'),
  TRANSLATION_SERVICE_TYPE: Symbol('TRANSLATION_SERVICE_TYPE'),
  TWITTER_SHARER_SERVICE_TYPE: Symbol('TWITTER_SHARER_SERVICE_TYPE'),
  HTML_PARSER_SERVICE_TYPE: Symbol('HTML_PARSER_SERVICE_TYPE'),
  FILE_LOADER_TYPE: Symbol('FILE_LOADER_TYPE'),
  LANGUAGE_SERVICE_TYPE: Symbol('LANGUAGE_SERVICE_TYPE'),
  TALKS_REPOSITORY_TYPE: Symbol('TALKS_REPOSITORY_TYPE'),
  ARTICLES_REPOSITORY_TYPE: Symbol('ARTICLES_REPOSITORY_TYPE'),
  GET_ALL_ARTICLES_USE_CASE_TYPE: Symbol('GET_ALL_ARTICLES_USE_CASE_TYPE'),
  GET_ARTICLE_USE_CASE_TYPE: Symbol('GET_ARTICLE_USE_CASE_TYPE'),
  GET_TALKS_GIVEN_USE_CASE_TYPE: Symbol('GET_TALKS_GIVEN_USE_CASE_TYPE'),
  USE_CASE_DECORATOR_TYPE: Symbol('USE_CASE_DECORATOR_TYPE'),
  LOGGER_TYPE: Symbol('LOGGER_TYPE'),
  STDOUT_TYPE: Symbol('STDOUT_TYPE')
}
