export const TYPES = {
  TALKS_REPOSITORY: Symbol.for('TALKS_REPOSITORY'),
  PREFERENCES_REPOSITORY: Symbol.for('PREFERENCES_REPOSITORY'),
  ARTICLES_REPOSITORY: Symbol.for('ARTICLES_REPOSITORY'),
  STORAGE: Symbol.for('STORAGE'),
}
