name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Configure npm
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPMRC_GITHUB_TOKEN }}" > ~/.npmrc
          echo "@cesalberca:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: compile
        run: npm run compile
      - name: test
        run: npm test
